version: '3.3'
services:
  phila_web_store_api:
    container_name: phila-web-store
    image: phila-web-store
    build: ./
    ports:
      - "8045:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_PASSWORD=phila
      - POSTGRES_USER=postgres
      - POSTGRES_DB=phila_web_storeDB
